version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor:
      name: node/default
      tag: << matrix.version >>
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Lint code
      - run:
          command: npm run build
          name: Build app
      - run:
          command: npm test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              version: ['18', '20']
          filters:
            branches:
              only: main
