version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  build_and_test:
    parameters:
      node-version:
        type: string
        default: '18'
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          node-version: << parameters.node-version >>
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build --if-present
      - run:
          name: Test
          command: npm test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              node-version: ['18', '20']
          filters:
            branches:
              only:
                - main
