version: 2.1

executors:
  node-executor:
    docker:
      - image: 'cimg/node:<< parameters.node-version >>'
    parameters:
      node-version:
        type: string
        default: '18.0'
jobs:
  build-and-test:
    executor: node-executor
    parameters:
      node-version:
        type: string
        default: '18.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              node-version: ['18.0', '20.0']
